name: 'Create packages'
on:
  workflow_call:
    inputs:
      event-ref:  
        description: 'github.event.ref'
        required: true
        type: string
      ref-name:  
        description: 'github.ref_name'
        required: true
        type: string

env:
  CACHE_NAME: cache-packages
  ALPHA_RELEASE: 0.0.1

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Set current date as env variable
        run: echo "ALPHA_RELEASE=$(date +'%-H%M%S')" >> $GITHUB_ENV
        if: startsWith(inputs.event-ref, 'refs/tags/v') != true
           
  create:
    needs: version
    runs-on: ubuntu-latest
    steps:     
        
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
              
      - name: Restore dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet build --no-restore
        
      - name: Create live Package
        run: dotnet pack --configuration Release
        if: startsWith(inputs.event-ref, 'refs/tags/v')
          
      - name: Create alpha Package
        run: |
          echo "a${{ env.ALPHA_RELEASE }}"
          dotnet pack --configuration Release --version-suffix "alpha.${{ env.ALPHA_RELEASE }}"
        if: startsWith(inputs.event-ref, 'refs/tags/v') != true
        
      - name: Cache
        uses: actions/cache@v3        
        with:        
         path: ~/
         key: ${{ env.CACHE_NAME }}      
        
  publish:
    runs-on: ubuntu-latest
    needs: create
    steps:   
     - name: Setup .NET
       uses: actions/setup-dotnet@v2
       with:
         dotnet-version: 6.0.x
         
     - name: Restore
       uses: actions/cache@v3
       with:
         path: ~/
         key: ${{ env.CACHE_NAME }}    

     - name: Delete release packages
       uses: Digital-Secure-Systems-Limited/CI-Actions-DeleteRepoPackageVersion@main
       id: delete nuget
       with:
          package-token: ${{ github.token }}
          package-version: ${{ github.ref_name }}
       if: startsWith(inputs.event-ref, 'refs/tags/v')
         
     - name: Publish
       run: dotnet nuget push "**/*.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --source "github" --skip-duplicate -n

